---
- name: Create new groups, users on remote hosts
  hosts: renamed,!taz
  gather_facts: no
  connection: ssh
  become: true

  tasks:
    - name: Ensure group "funkytown" exists
      ansible.builtin.group:
        name: funkytown
        state: present

    - name: Create new user
      ansible.builtin.user:
        name: AlanZ
        comment: AlanZ
        group: funkytown
